version: '3'
services:
  nexus:
      image: sonatype/nexus3
      container_name: nexus
      ports:
        - "8081:8081"
        - "8082:8082"
        - "8083:8083"
        - "8084:8084"
      volumes:
        - nexus-data:/nexus-data
      networks:
        -  jenkins-install_devops_net 
      restart: always

networks:
   jenkins-install_devops_net:
      external: true
volumes:
  nexus-data: 
