version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
    dns:
      - 8.8.8.8
      - 1.0.0.1
    volumes:
      - jenkins-data:/var/jenkins_home/
    networks:
      - jenkins-net
    restart: always

volumes:
  jenkins-data: {}

networks:
  jenkins-net: {}