---
language: python
python: "2.7"

sudo: required
dist: trusty

install:
  - pip install ansible
  - echo "localhost" > ansible.hosts
  - 'printf "[defaults]\nroles_path=../" > ansible.cfg'
  - ansible-galaxy install -p "../" bobbyrenwick.pip
  - ansible --version

script:
  - ansible-playbook tests/playbook.yml --syntax-check -i ansible.hosts -v
  - ansible-playbook tests/playbook.yml -i ansible.hosts -v
