version: '3'
services:
  nexus:
      image: sonatype/nexus3
      container_name: nexus
      ports:
        - "8081:8081"
        - "8082:8082"
        - "8083:8083"
        - "8084:8084"
      volumes:
        - nexus-data:/nexus-data
      networks:
        - nexus-net 
      restart: unless-stopped

networks:
  nexus-net: {}
volumes:
  nexus-data: 
