
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'petclinic-app'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'app'
        type: 'A'
        port: 8080

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-primary'
    static_configs:
      - targets: ['postgres-exporter-primary:9187']

  - job_name: 'postgres-replica'
    static_configs:
      - targets: ['postgres-exporter-replica:9187']

