- name: Ensure swap is configured
  block:
    - name: Create a 2GB swap file
      ansible.builtin.command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile

    - name: Set the correct permissions for the swap file
      ansible.builtin.file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: Format the file as swap
      ansible.builtin.command: mkswap /swapfile

    - name: Enable the swap file
      ansible.builtin.command: swapon /swapfile

    - name: Make the swap file permanent in /etc/fstab
      ansible.posix.mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        state: present
  when: ansible_swaptotal_mb < 100
