version: '3'
services:
  jenkins:
    build:
      context: ./
    container_name: jenkins
    ports:
      - '8080:8080'
    dns:
      - 8.8.8.8
      - 1.0.0.1
    volumes:
      - 16_jenkins_try_jenkins-data:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins-net
      - nexus-net
    restart: always

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    env_file:
      - ./sonar.env
    container_name: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonar-net
      - jenkins-net
    restart: always
  
  db:
    image: postgres:12
    container_name: postgresql
    env_file:
      - ./postgres.env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-net
    ports: 
      - "5432:5432"
    restart: always
  
  nexus:
      image: sonatype/nexus3
      container_name: nexus
      ports:
        - "8081:8081"
        - "8082:8082"
        - "8083:8083"
        - "8084:8084"
        - "8085:8085"
      volumes:
        - nexus_nexus-data:/nexus-data
      networks:
        - nexus-net 
      restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  nexus_nexus-data:
    external: true
  16_jenkins_try_jenkins-data:
    external: true

 
networks:
  sonar-net:
  nexus-net:
  jenkins-net: